#!/bin/bash

# 0x3 ESP8266 Advanced Project Setup Script
# This script helps you quickly set up a new project based on the advanced ESP8266 template
# It configures all modern features including WiFi, mDNS, OTA, API endpoints, and more

set -e

echo "🚀 0x3 Advanced ESP8266 Project Setup"
echo "====================================="
echo "Version: 2.0.0"
echo "Author: 0x3"
echo

# Function to prompt for input with default value
prompt_with_default() {
    local prompt="$1"
    local default="$2"
    local result
    
    if [ -n "$default" ]; then
        read -p "$prompt [$default]: " result
        echo "${result:-$default}"
    else
        read -p "$prompt: " result
        echo "$result"
    fi
}

# Function to validate hostname
validate_hostname() {
    local hostname="$1"
    if [[ "$hostname" =~ ^[a-z0-9-]+$ ]] && [[ ${#hostname} -le 63 ]]; then
        return 0
    else
        return 1
    fi
}

# Function to generate secure password
generate_password() {
    local length=${1:-12}
    openssl rand -base64 $length | tr -d "=+/" | cut -c1-$length
}

echo "📋 Project Configuration"
echo "------------------------"

# Get project details
PROJECT_NAME=$(prompt_with_default "Project Name" "MyESP8266Project")
PROJECT_VERSION=$(prompt_with_default "Project Version" "1.0.0")
PROJECT_AUTHOR=$(prompt_with_default "Author/Organization" "$(whoami)")

# Get network configuration
while true; do
    HOSTNAME=$(prompt_with_default "Device Hostname (lowercase, no spaces)" "$(echo "$PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-')")
    if validate_hostname "$HOSTNAME"; then
        break
    else
        echo "❌ Invalid hostname. Use only lowercase letters, numbers, and hyphens."
    fi
done

# Security configuration
echo
echo "🔒 Security Configuration"
echo "-------------------------"
echo "Generate secure passwords? (recommended for production) [y/N]"
read -r GENERATE_SECURE

if [[ "$GENERATE_SECURE" =~ ^[Yy]$ ]]; then
    AP_PASSWORD=$(generate_password 16)
    OTA_USERNAME="admin"
    OTA_PASSWORD=$(generate_password 16)
    echo "✅ Generated secure passwords"
else
    AP_PASSWORD=$(prompt_with_default "Configuration AP Password" "0x3Config")
    OTA_USERNAME=$(prompt_with_default "OTA Username" "admin")
    OTA_PASSWORD=$(prompt_with_default "OTA Password" "0x3Update")
fi

# Board selection
echo
echo "🔧 Board Selection"
echo "------------------"
echo "Select your ESP8266 board:"
echo "1) Wemos D1 Mini (default)"
echo "2) NodeMCU v2"
echo "3) ESP-12E"
echo "4) ESP-01 (1MB)"
echo "5) Custom"

read -p "Board choice [1]: " BOARD_CHOICE
BOARD_CHOICE=${BOARD_CHOICE:-1}

case $BOARD_CHOICE in
    1)
        BOARD="d1_mini"
        BOARD_NAME="Wemos D1 Mini"
        LED_PIN=2
        ;;
    2)
        BOARD="nodemcuv2"
        BOARD_NAME="NodeMCU v2"
        LED_PIN=2
        ;;
    3)
        BOARD="esp12e"
        BOARD_NAME="ESP-12E"
        LED_PIN=2
        ;;
    4)
        BOARD="esp01_1m"
        BOARD_NAME="ESP-01"
        LED_PIN=1
        echo "⚠️  ESP-01 has limited memory. Some features may be reduced."
        ;;
    5)
        BOARD=$(prompt_with_default "Custom board identifier" "d1_mini")
        BOARD_NAME=$(prompt_with_default "Custom board name" "Custom ESP8266")
        LED_PIN=$(prompt_with_default "LED pin number" "2")
        ;;
esac

# Summary
echo
echo "📝 Configuration Summary"
echo "------------------------"
echo "Project Name:     $PROJECT_NAME"
echo "Version:          $PROJECT_VERSION"
echo "Author:           $PROJECT_AUTHOR"
echo "Hostname:         $HOSTNAME"
echo "Board:            $BOARD_NAME ($BOARD)"
echo "LED Pin:          $LED_PIN"
echo "AP Password:      $AP_PASSWORD"
echo "OTA Username:     $OTA_USERNAME"
echo "OTA Password:     $OTA_PASSWORD"
echo

read -p "Continue with this configuration? [Y/n]: " CONFIRM
if [[ "$CONFIRM" =~ ^[Nn]$ ]]; then
    echo "❌ Setup cancelled"
    exit 1
fi

echo
echo "⚙️  Configuring project..."

# Update config.h
cat > include/config.h << EOF
#ifndef CONFIG_H
#define CONFIG_H

// 0x3 Advanced ESP Project Configuration
// Generated by setup script on $(date)

// Project Information
#define PROJECT_NAME "$PROJECT_NAME"
#define PROJECT_VERSION "$PROJECT_VERSION"
#define PROJECT_AUTHOR "$PROJECT_AUTHOR"

// WiFi Configuration
#define WIFI_TIMEOUT 30000          // 30 seconds
#define WIFI_RETRY_DELAY 5000       // 5 seconds
#define AP_PASSWORD "$AP_PASSWORD"
#define CONFIG_PORTAL_TIMEOUT 300   // 5 minutes

// OTA Configuration
#define OTA_USERNAME "$OTA_USERNAME"
#define OTA_PASSWORD "$OTA_PASSWORD"
#define OTA_PORT 8080

// Web Server Configuration
#define WEB_SERVER_PORT 80
#define API_ENDPOINT_PREFIX "/api/v1"  // Advanced API version endpoint

// Hardware Configuration
#define LED_BUILTIN $LED_PIN        // Built-in LED pin for status indication
#define STATUS_LED_PIN LED_BUILTIN

// Debug Configuration
#define DEBUG_ENABLED true
#define DEBUG_BAUD_RATE 115200

// Network Configuration
#define HOSTNAME "$HOSTNAME"
#define MDNS_ENABLED true          // Enable mDNS for service discovery
#define MDNS_SERVICE "_http"       // mDNS service type
#define MDNS_PROTOCOL "_tcp"       // mDNS protocol

// Timing Configuration
#define HEARTBEAT_INTERVAL 30000    // 30 seconds
#define STATUS_UPDATE_INTERVAL 5000 // 5 seconds
#define SYSTEM_INFO_COLLECTION_INTERVAL 60000 // 60 seconds

// Advanced Features
#define ENABLE_JSON_LOGGING true    // Enable JSON logging to serial
#define MAX_LOG_ENTRIES 100         // Maximum number of log entries to keep in memory
#define ENABLE_TELEMETRY true       // Enable telemetry data collection

#endif // CONFIG_H
EOF

# Update platformio.ini with selected board
sed -i.bak "s/board = d1_mini/board = $BOARD/" platformio.ini
rm platformio.ini.bak

echo "✅ Configuration updated!"
echo

# Build test
echo "🔨 Testing build..."
if platformio run > /dev/null 2>&1; then
    echo "✅ Build successful!"
else
    echo "❌ Build failed. Please check your configuration."
    exit 1
fi

echo
echo "🎉 Setup Complete!"
echo "=================="
echo
echo "Next steps:"
echo "1. Connect your $BOARD_NAME to your computer"
echo "2. Upload firmware: platformio run --target upload"
echo "3. Monitor serial output: platformio device monitor"
echo "4. Configure WiFi via the device's AP: $HOSTNAME_[ChipID]"
echo "5. Access web interface at the device's IP address"
echo
echo "Configuration Details:"
echo "- Device will create AP: $HOSTNAME_[ChipID]"
echo "- AP Password: $AP_PASSWORD"
echo "- OTA Username: $OTA_USERNAME"
echo "- OTA Password: $OTA_PASSWORD"
echo "- Web interface: http://[device-ip]"
echo "- OTA updates: http://[device-ip]/update"
echo
echo "📚 Documentation:"
echo "- Main README: README.md"
echo "- Template Guide: TEMPLATE_USAGE.md"
echo "- Build instructions: Look for platformio commands above"
echo
echo "🔒 Security Note:"
if [[ "$GENERATE_SECURE" =~ ^[Yy]$ ]]; then
    echo "Secure passwords have been generated. Save them safely!"
else
    echo "Consider using stronger passwords for production deployment."
fi
echo
echo "Happy coding! 🚀"
EOF
